### ISSUE TITLE
... but how do we use it?

### ISSUE THREAD

**Issue by bpmartin20** [nextcloud/privacy#1058]
This sounds like an interesting app ... but can we have some instructions on how to invoke it, please? Right now, if I click on it in my NextCloud apps, I get a fine one-sentence description of what it does, but nothing on how I use it. Do I right click on a file to see where it's shared? Do I launch the app somehow? Is it a report that I need to schedule? Privacy is apparently installed on my NC instance, but I don't where to find it.

At a minimum, please add how to see the information this app provides to the existing description. Better would be to also have a "visit website" or "see in app store" link with screen shots and instructions. For a good example, check out how what happens when  you click on "Notes" in NextCloud Apps. (And I really like the "Changelog" tab that many apps have, too.)

This sounds like a fine app. Thank you for developing it. I look forward to checking it out.

**Comment by skjnldsv** [comment]
Once enabled you have a section in your settings:
![image](https://github.com/nextcloud/privacy/assets/14975046/d3e930c8-0c2f-4825-82a2-39dce6eb66e9)

**Comment by bpmartin20** [comment]
Very good. Then would it be possible to amend the current description to add something like: 

    Once installed, a new "Privacy" item appears in each user's "Personal Settings".
