### ISSUE TITLE
Better description and communication

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/privacy#131]
This app was automatically installed and activated when updating from Nextcloud v15.x to v16.x. But it is unclear what this app does.

* A description is missing under `/index.php/settings/apps/enabled/privacy`
* Link to `View in store` is broken
* This GitHub Repository has no description
* The README.md contains build instructions, but no description of what the purpose is

Something like that should never be released... Don't get me wrong, I can figure out for myself what this app does. But many others can't.

**Comment by georgehrke** [comment]
> A description is missing under /index.php/settings/apps/enabled/privacy

fixed in #132 

> Link to View in store is broken

Bug in Nextcloud server, will be fixed with 16.0.2 (https://github.com/nextcloud/server/pull/15582)

> This GitHub Repository has no description

fixed in #132
