### ISSUE TITLE
not compatible with Nextcloud 16.0.2

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/privacy#158]
The update notifications for Nextcloud 16.0.2 does show that this app is not yet compatible with Nextcloud 16.0.2 therefore I could not yet migrate our instance to 16.0.2

**Comment by GuidoDr** [comment]
is this eventually still the same problem like it had been with 16.0.1 ([issue 118](https://github.com/nextcloud/privacy/issues/118))?

**Comment by gary-kim** [comment]
Yes, this is a duplicate of #118 
The issue has been fixed in Nextcloud 16.0.2. Don't worry, you can ignore the warning upgrade Nextcloud to 16.0.2 and the privacy app will still work.
