### ISSUE TITLE
Incomplete Country list

### ISSUE THREAD

**Issue by arenasa70** [nextcloud/privacy#241]
### Steps to reproduce
1. Login ad Administrator
2. Goto /settings/user/privacy
3. On the Where's your data section select a country, try Aruba, Curacao, Bonair, Sint Maarten

### Expected behaviour
Find any country,like in the ISO Country codes list https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

### Actual behaviour
A lot of countries can't be set.

### Server configuration

**Nextcloud version:** 16.0.5

**Where did you install Nextcloud from: linuxserver/nextcloud:amd64-latest Docker

**Comment by kesselb** [comment]
We could use something like: https://www.npmjs.com/package/country-codes-list

**Comment by georgehrke** [comment]
The solution proposed by @kesselb in https://github.com/nextcloud/privacy/pull/248 is the way to go, we just need to find a way to have the list of countries translated.

**Comment by TP75** [comment]
Do you know [GNU gettext](https://www.gnu.org/software/gettext/) ?

- https://www.php.net/manual/de/book.gettext.php
- https://www.a-coding-project.de/ratgeber/php/lokalisierung-mit-gettext

**Comment by georgehrke** [comment]
@TP75 Please see my comments in https://github.com/nextcloud/privacy/pull/248
I don't see how gettext can help us there. We already have a way of extracting translatable strings, the problem is that the strings that we need to translate are hidden deep inside a npm module not following our standard.

**Comment by TP75** [comment]
> @TP75 Please see my comments in #248

Please accept my apologies. However, IMHO the comments look too basic for me to truly grasp the issue.

One may not underestimate the power and flexibility of the `gettext` library ans set of function.  I trust the NC developers in being agile and flexible.

Happy hacking.
🌻
