### ISSUE TITLE
Doesn't allow an statement on privacy from administrators

### ISSUE THREAD

**Issue by oriold** [nextcloud/privacy#261]
It indicates who are the administrators but no way to point which policy in place regarding the administrators access to data.

**Comment by georgehrke** [comment]
The theming app already allows setting a link to a privacy policy. Should we just display the same Url in the privacy app?

**Comment by oriold** [comment]
Ok I will investigate that I think it would be helpful to be able to edit something from there though.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/privacy/blob/master/templates/who-has-access.php#L12

This is actually the case already. If you set a link to a privacy URL in theming, it will show up on the login site as well as the privacy app.
